services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pguser"]
      interval: 10s
      timeout: 5s
      retries: 5
    